# Generated by Django 4.2.9 on 2026-04-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_rename_anio_vigencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='contrasena',
            field=models.CharField(default='123456', max_length=128, verbose_name='Contraseña'),
        ),
    ]
