# Generated by Django 4.2.9 on 2026-04-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_estudiante_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='transaccion_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Transacción Externo'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
    ]
