# Generated by Django 4.2.9 on 2026-04-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0005_boleta_transaccion_id_alter_inscripcion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatSelec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_serie', models.CharField(max_length=50, verbose_name='Número de Serie de Inscripción')),
                ('registro', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel', models.IntegerField(default=0, verbose_name='Nivel/Semestre')),
                ('cod_mat', models.IntegerField(verbose_name='Código de Materia')),
                ('plan', models.CharField(max_length=10, verbose_name='Plan de Estudios')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('nombre_materia', models.CharField(max_length=200, verbose_name='Nombre Materia')),
                ('grupo', models.CharField(max_length=10, verbose_name='Grupo')),
                ('estado', models.CharField(default='I', max_length=5, verbose_name='Estado (Proceso)')),
                ('ok', models.IntegerField(default=1, verbose_name='OK (Confirmado)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Materia Seleccionada',
                'verbose_name_plural': 'Materias Seleccionadas',
                'db_table': 'mat_selec',
                'unique_together': {('nro_serie', 'cod_mat', 'grupo')},
            },
        ),
    ]
