# Generated by Django 4.2.9 on 2026-02-05 18:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código de Carrera')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Carrera')),
                ('facultad', models.CharField(max_length=200, verbose_name='Facultad')),
                ('duracion_semestres', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Duración en Semestres')),
                ('activa', models.BooleanField(default=True, verbose_name='Carrera Activa')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('registro', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Registro Universitario')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido Materno')),
                ('semestre_actual', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Semestre Actual')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('SEMIPRESENCIAL', 'Semipresencial'), ('VIRTUAL', 'Virtual')], default='PRESENCIAL', max_length=20)),
                ('lugar_origen', models.CharField(max_length=200, verbose_name='Lugar de Origen')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Estudiante Activo')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('carrera_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='inscripcion.carrera')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='Código de Materia')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Materia')),
                ('creditos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Créditos')),
                ('horas_teoricas', models.IntegerField(default=0, verbose_name='Horas Teóricas')),
                ('horas_practicas', models.IntegerField(default=0, verbose_name='Horas Prácticas')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código del Periodo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Periodo')),
                ('tipo', models.CharField(choices=[('1/2024', 'Primer Semestre 2024'), ('2/2024', 'Segundo Semestre 2024'), ('1/2025', 'Primer Semestre 2025'), ('2/2025', 'Segundo Semestre 2025'), ('1/2026', 'Primer Semestre 2026'), ('2/2026', 'Segundo Semestre 2026')], max_length=10, verbose_name='Tipo de Periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('activo', models.BooleanField(default=False, verbose_name='Periodo Activo')),
                ('inscripciones_habilitadas', models.BooleanField(default=False, verbose_name='Inscripciones Habilitadas')),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del Plan')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Plan')),
                ('anio_vigencia', models.IntegerField(verbose_name='Año de Vigencia')),
                ('vigente', models.BooleanField(default=True, verbose_name='Plan Vigente')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='inscripcion.carrera')),
            ],
            options={
                'verbose_name': 'Plan de Estudios',
                'verbose_name_plural': 'Planes de Estudio',
                'ordering': ['-anio_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion_asignada', models.DateField(verbose_name='Fecha de Inscripción Asignada')),
                ('fecha_inscripcion_realizada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inscripción Realizada')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('bloqueado', models.BooleanField(default=False, verbose_name='Estado de Bloqueo')),
                ('motivo_bloqueo', models.TextField(blank=True, verbose_name='Motivo del Bloqueo')),
                ('boleta_generada', models.BooleanField(default=False, verbose_name='Boleta Generada')),
                ('numero_boleta', models.CharField(blank=True, max_length=50, verbose_name='Número de Boleta')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='inscripcion.estudiante')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='inscripcion.periodoacademico')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion_asignada'],
                'unique_together': {('estudiante', 'periodo_academico')},
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='plan_estudios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='inscripcion.planestudios'),
        ),
        migrations.CreateModel(
            name='MateriaCarreraSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Semestre')),
                ('obligatoria', models.BooleanField(default=True, verbose_name='Materia Obligatoria')),
                ('habilitada', models.BooleanField(default=True, verbose_name='Materia Habilitada')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_semestre', to='inscripcion.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras_semestre', to='inscripcion.materia')),
                ('plan_estudios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_semestre', to='inscripcion.planestudios')),
            ],
            options={
                'verbose_name': 'Materia por Carrera y Semestre',
                'verbose_name_plural': 'Materias por Carrera y Semestre',
                'ordering': ['semestre', 'materia__codigo'],
                'unique_together': {('carrera', 'plan_estudios', 'materia', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='InscripcionMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(default='A', max_length=5, verbose_name='Grupo')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_inscritas', to='inscripcion.inscripcion')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='inscripcion.materia')),
            ],
            options={
                'verbose_name': 'Materia Inscrita',
                'verbose_name_plural': 'Materias Inscritas',
                'unique_together': {('inscripcion', 'materia')},
            },
        ),
    ]
