# Generated by Django 4.2.9 on 2026-02-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FINANCIERO', 'Deuda Financiera'), ('ACADEMICO', 'Bloqueo Académico'), ('ADMINISTRATIVO', 'Bloqueo Administrativo'), ('DISCIPLINARIO', 'Bloqueo Disciplinario')], max_length=20, verbose_name='Tipo de Bloqueo')),
                ('motivo', models.TextField(verbose_name='Motivo del Bloqueo')),
                ('fecha_bloqueo', models.DateField(auto_now_add=True, verbose_name='Fecha de Bloqueo')),
                ('fecha_desbloqueo_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Desbloqueo Estimada')),
                ('activo', models.BooleanField(default=True, verbose_name='Bloqueo Activo')),
                ('resuelto', models.BooleanField(default=False, verbose_name='Bloqueo Resuelto')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='inscripcion.estudiante')),
            ],
            options={
                'verbose_name': 'Bloqueo',
                'verbose_name_plural': 'Bloqueos',
                'ordering': ['-fecha_bloqueo'],
            },
        ),
    ]
