# Generated by Django 4.2.9 on 2026-02-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_bloqueo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta_pago', to='inscripcion.inscripcion')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
            },
        ),
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Obligatorio')),
            ],
            options={
                'verbose_name': 'Concepto de Pago',
                'verbose_name_plural': 'Conceptos de Pago',
            },
        ),
        migrations.AlterField(
            model_name='inscripcionmateria',
            name='grupo',
            field=models.CharField(blank=True, default='A', max_length=5, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='inscripcionmateria',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_directas', to='inscripcion.materia'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='tipo',
            field=models.CharField(choices=[('1/2026', 'Primer Semestre 2026'), ('2/2026', 'Segundo Semestre 2026'), ('1/2025', 'Primer Semestre 2025'), ('2/2025', 'Segundo Semestre 2025')], max_length=10, verbose_name='Tipo de Periodo'),
        ),
        migrations.CreateModel(
            name='OfertaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=5, verbose_name='Grupo')),
                ('docente', models.CharField(default='Por designar', max_length=100, verbose_name='Docente')),
                ('horario', models.CharField(default='HORARIO A CONFIRMAR', max_length=100, verbose_name='Horario')),
                ('cupo_maximo', models.IntegerField(default=40, verbose_name='Cupo Máximo')),
                ('cupo_actual', models.IntegerField(default=0, verbose_name='Cupo Actual')),
                ('materia_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='inscripcion.materiacarrerasemestre')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='inscripcion.periodoacademico')),
            ],
            options={
                'verbose_name': 'Oferta de Materia',
                'verbose_name_plural': 'Ofertas de Materias',
                'ordering': ['materia_carrera__materia__codigo', 'grupo'],
                'unique_together': {('materia_carrera', 'periodo', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Aplicado')),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inscripcion.boleta')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletas', to='inscripcion.conceptopago')),
            ],
            options={
                'verbose_name': 'Detalle de Boleta',
                'verbose_name_plural': 'Detalles de Boleta',
            },
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionmateria',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inscripcionmateria',
            name='oferta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='inscripcion.ofertamateria'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionmateria',
            unique_together={('inscripcion', 'oferta')},
        ),
    ]
